version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [[properties]]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#6c6c6c'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}↓{{end}}{{if gt .Ahead 0 }}↑{{end}}</>'

    [[properties]]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

[[blocks.segments]]
  type = 'text'
  syle = 'plain'
  foreground_templates  = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}blue{{end}}",
  ]
  background = 'transparent'
  template = "❭"

[transient_prompt]
  foreground = 'blue'
  background = 'transparent'
  template = "❭ "


  [[blocks]]
type = "rprompt"

  [[blocks.segments]]
  foreground = "blue"
  template = " {{ .CurrentDate | date .Format }} "
  style = "plain"
  type = "time"

    [blocks.segments.properties]
    time_format = "15:04:05"


blocks = [ ]

[[tooltips]]
type = "git"
tips = [ "git", "g" ]
style = "diamond"
foreground = "blue"
background = "transparent"
leading_diamond = ""
trailing_diamond = ""
template = "{{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}"

  [tooltips.properties]
  fetch_status = true
  fetch_upstream_icon = true


  blocks = [ ]

[[tooltips]]
type = "aws"
tips = [ "aws", "terraform" ]
style = "plain"
foreground = "#e0af68"
template = "f {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"

[[tooltips]]
type = "az"
tips = [ "az", "terraform" ]
style = "plain"
foreground = "#b4f9f8"
template = " {{ .Name }}"
